spring.application.name=bloom-user-service

spring.datasource.url=jdbc:postgresql://localhost:5432/bloom_db
spring.datasource.username=bloom
spring.datasource.password=bloom123
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

server.port=${SERVER_PORT:8081}